### PR TITLE
Allow to use local GTFS files & fix the licence in package.json

### PR DESCRIPTION
**Pull request by j33f**
By using ```path``` instead of ```url``` in config file, you can now use local GTFS files 

```{ agency_key: 'localAgency', path: '/path/to/the/gtfs.zip'}```

### CODE REVIEW

**Comment by brendannee** [comment]
Cool - can you give me an example of an agency where the 'FixCoordinates' function is needed?

**Comment by j33f** [comment]
http://data.angers.fr/donnees/mobilite-horaire-de-passage-theorique/?tx_icsoddatastore_pi1[keywords]=&tx_icsoddatastore_pi1[managers][0]=19

This dataset from Angers, in France, used to be in Lambert II projection. (they correct it just today, of course...)

In France, it is quite usual to get badly formatted GTFS and Lambert II as projection...

**Comment by brendannee** [comment]
I merged in your code:

* The merge didn't apply cleanly since I had made some new commits since you forked the repo, so did a bit of to pull this in.

* You can now specify a local .zip or unzipper gtfs file by specifying a `path` attribute - the readme is updated to reflect this.

* Specifying a proj4 string is now supported - if you would like to please make a pull request to the readme to add more information on how to do this, and how to tell if the GTFS file you are working with needs this.

* I didn't include the code you had for fixing station/stop coordinates - are there a lot of GTFS files you work with where stops that are stations don't have coordinates supplied?

**Comment by j33f** [comment]
Yep it is very common to see stations with no coordinates at the end of the stops file when you are using french GTFS... :(

Anyway,  imho, it is always a good idea to have some integrated fail safe mechanism included in this kind of tool. You never know where the data will come from, nor if they are clean. When it is possible to fix things by a simple way, why not do it ?

**Comment by brendannee** [comment]
Cool - can you send me an example GTFS file for an agency with stations
that have no coordinates so I can test against it?

**Comment by j33f** [comment]
here is one https://modulaweb.fr/cloud/index.php/s/WWskixX1qb15nmO it also have coordinates in Lambert II projection...

**Pull request merged**
